### ISSUE TITLE
讨论区需要使用websocket吗？

### ISSUE THREAD

**Issue by TheScientist1900** [i-m-feeling-lucky/online-interview#1]
我们需要实现一个类似于面试的功能，我看后端没有用到websocket和channels，也没有看到类似的视图处理函数，请问一下是如何实现的呢？

**Comment by yusanshi** [comment]
我们是用 https://github.com/muaz-khan/RTCMultiConnection 来实现的通信（聊天、白板等），核心代码在这里：<https://github.com/i-m-feeling-lucky/frontend/blob/master/src/views/Interview.vue#L542-L653>

**Comment by TheScientist1900** [comment]
通信部分只需要前端写吗？我看网上说django实现直播需要channels模块，但我看你们后端基本没用多少额外的模块。

**Comment by yusanshi** [comment]
由于我们用了 RTCMultiConnection 这个包，跟通信相关的所有东西都是在前端部分了（当然还需要有一台服务器专门用来跑 RTCMultiConnection server，用提供 RTC Socket URL）。

我们的前端部分倒是也有把通信的内容向后端传输的逻辑，但那个是为了保存面试内容用做之后的回放，和面试通信本身没有关系。
